name: Deploy

on:
  workflow_dispatch:
    inputs:
      videoID:
        description: 'Video ID'
        required: true
        type: string

jobs:
  Deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::961181693216:role/gh-actions-runner

      - name: Bootstrap CDK
        run: cdk bootstrap
        env:
          VIDEO_ID: ${{ github.event.inputs.videoID }}

      - name: CDK Synth
        run: cdk synth
        env:
          VIDEO_ID: ${{ github.event.inputs.videoID }}

      - name: CDK Diff
        run: cdk diff
        env:
          VIDEO_ID: ${{ github.event.inputs.videoID }}

      - name: Deploy CDK stack
        run: cdk deploy --require-approval never
        env:
          VIDEO_ID: ${{ github.event.inputs.videoID }}
