name: Deploy
on:
  workflow_dispatch:
    inputs:
      videoID:
        description: 'Video ID'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install wheel
      - name: Install CDK (Node)
        run: |
          npm install -g aws-cdk
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::961181693216:role/gh-actions-runner
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Synth
        run: |
          cdk synth
      - name: Diff
        run: |
          cdk diff
      - name: Deploy
        run: |
          cdk deploy --require-approval never
